pref("extensions.nova-initia.debug", false);
pref("extensions.nova-initia.cur_username", "");
pref("extensions.nova-initia.cur_ava_url", "");
pref("extensions.nova-initia.cur_tagline", "");
pref("extensions.nova-initia.cur_location", "");
pref("extensions.nova-initia.cur_email", "");
pref("extensions.nova-initia.cur_class", "");
pref("extensions.nova-initia.cur_id", "");
pref("extensions.nova-initia.cur_hash", "");
pref("extensions.nova-initia.hotkey_trap", "1");
pref("extensions.nova-initia.hotkey_barrel", "2");
pref("extensions.nova-initia.hotkey_signpost", "6");
pref("extensions.nova-initia.hotkey_doorway", "5");
pref("extensions.nova-initia.hotkey_spider", "3");
pref("extensions.nova-initia.hotkey_shield", "4");
pref("extensions.nova-initia.hotkey_modifier_ctrl", true);
pref("extensions.nova-initia.hotkey_modifier_alt", false);
pref("extensions.nova-initia.hotkey_modifier_shift", false);
pref("extensions.nova-initia.login_saved", false);
pref("extensions.nova-initia.login_toolbar_visible_at_startup", true);
pref("extensions.nova-initia.saved_password_hash", "");
pref("extensions.nova-initia.saved_username", "");
pref("extensions.nova-initia.toolbar_text_orientation_vertical",false);
pref("extensions.nova-initia.server_url", "nova-initia.com");
pref("extensions.nova-initia.url_prefix", "data.");
pref("extensions.nova-initia.stash_barrel_button_placement_bottom", false);
pref("extensions.nova-initia.filter_nsfw_all",true);